[package]
name = "darkhttpd"
version = "0.1.0"
authors = ["Tom Dryer <tomdryer.com@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
chrono = "0.4.19"
nix = "0.20.0"
anyhow = "1.0.40"

[dev-dependencies]
tempfile = "3"
test-case = "1.1.0"
